- id: flake8-ros
  name: flake8 ros
  description: Apply flake8 with the ROS 2 settings.
  entry: flake8
  language: python
  types: [python]
  require_serial: true
  additional_dependencies:
    [
      flake8==4.0.1,
      flake8-blind-except,
      flake8-builtins,
      flake8-class-newline,
      flake8-comprehensions,
      flake8-deprecated,
      flake8-docstrings,
      flake8-import-order,
      flake8-quotes,
    ]

- id: prettier-xacro
  name: prettier xacro
  description: Apply Prettier with plugin-xml to xacro.
  entry: prettier --write --list-different --ignore-unknown --print-width 200 --xml-self-closing-space false --xml-whitespace-sensitivity ignore
  language: node
  files: .xacro$
  additional_dependencies: [prettier@2.6.2, "@prettier/plugin-xml@2.0.1"]

- id: prettier-launch-xml
  name: prettier launch.xml
  description: Apply Prettier with plugin-xml to launch.xml.
  entry: prettier --write --list-different --ignore-unknown --print-width 200 --xml-self-closing-space false --xml-whitespace-sensitivity ignore
  language: node
  files: launch.xml$
  additional_dependencies: [prettier@2.6.2, "@prettier/plugin-xml@2.0.1"]

- id: prettier-package-xml
  name: prettier package.xml
  description: Apply Prettier with plugin-xml to package.xml.
  entry: prettier --write --list-different --ignore-unknown --print-width 1000 --xml-self-closing-space false --xml-whitespace-sensitivity ignore
  language: node
  files: package.xml$
  additional_dependencies: [prettier@2.6.2, "@prettier/plugin-xml@2.0.1"]

- id: ros-include-guard
  name: fix include guard
  description: Fix the include guard macro name.
  entry: ros-include-guard
  language: python
  files: .*\.(h|hpp)$

- id: sort-package-xml
  name: sort package.xml
  description: Sort the dependent packages in package.xml.
  entry: sort-package-xml
  language: python
  files: package.xml$
