- id: prettier-xacro
  name: prettier xacro
  description: Apply Prettier with plugin-xml to xacro.
  entry: prettier --write --list-different --ignore-unknown --print-width 120 --xml-self-closing-space false
  language: node
  files: .xacro$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: prettier-launch-xml
  name: prettier launch.xml
  description: Apply Prettier with plugin-xml to launch.xml.
  entry: prettier --write --list-different --ignore-unknown --print-width 200 --xml-self-closing-space false
  language: node
  files: launch.xml$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: prettier-package-xml
  name: prettier package.xml
  description: Apply Prettier with plugin-xml to package.xml.
  entry: prettier --write --list-different --ignore-unknown --print-width 1000 --xml-self-closing-space false
  language: node
  files: package.xml$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: sort-package-xml
  name: sort package.xml
  description: Sort the dependent packages in package.xml.
  entry: sort-package-xml
  language: python
  files: package.xml$

- id: ros-include-guard
  name: fix include guard
  description: Fix the include guard macro name.
  entry: ros-include-guard
  language: python
  files: .*\.(h|hpp)$
