- id: prettier-xacro
  name: Prettier xacro
  description: Apply prettier to xacro
  entry: prettier --write --list-different --ignore-unknown --print-width 120 --xml-self-closing-space false
  language: node
  files: .xacro$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: prettier-launch-xml
  name: Prettier launch.xml
  description: Apply prettier to launch.xml
  entry: prettier --write --list-different --ignore-unknown --print-width 200 --xml-self-closing-space false
  language: node
  files: launch.xml$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: prettier-package-xml
  name: Prettier package.xml
  description: Apply prettier to package.xml
  entry: prettier --write --list-different --ignore-unknown --print-width 1000 --xml-self-closing-space false
  language: node
  files: package.xml$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: sort-package-xml
  name: Sort package.xml
  language: python
  entry: sort-package-xml
  description: Sort package.xml
  files: package.xml$
