- id: check-gitmodules
  name: check gitmodules
  description: Check .gitmodules for proper submodule configuration (name matches path, has branch or update=none).
  entry: check-gitmodules
  language: python
  files: \.gitmodules$
  pass_filenames: false
