- id: prettier-xml
  name: Prettier XML
  description: Apply prettier to package.xml
  entry: prettier --write --list-different --ignore-unknown --print-width 1000 --xml-self-closing-space false
  language: node
  files: package.xml$
  additional_dependencies: ["prettier@2.4.1", "@prettier/plugin-xml@1.1.0"]

- id: sort-package-xml
  name: Sort package.xml
  language: python
  entry: sort-package-xml
  description: Sort package.xml
  files: package.xml$
