name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    uses: tier4/autoware-github-actions/.github/workflows/reusable-semantic-pull-request.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
