name: test-pre-commit-hooks

on:
  pull_request:

jobs:
  test-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@v1
        with:
          pre-commit-config: tests/pre-commit-hooks/test-pre-commit-hooks.yaml
